# This is a basic workflow to help you get started with Actions

name: Free5gc CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: git clone free5gc
        run: |
          sudo -E apt-get install -y mongodb wget git
          sudo -E apt-get install -y gcc cmake autoconf libtool pkg-config libmnl-dev libyaml-dev
          cd /tmp
          git clone -b master https://github.com/free5gc/free5gc.git
          cd /tmp/free5gc
          git submodule update --init --recursive
          cd /tmp
          git clone -b v0.1.0 https://github.com/PrinzOwO/gtp5g.git 
          
          cd /tmp/free5gc
          go vet ./src/amf/... 
          go vet ./src/ausf/... 
          go vet ./src/nrf/... 
          go vet ./src/nssf/... 
          go vet ./src/pcf/... 
          go vet ./src/smf/... 
          go vet ./src/udm/... 
          go vet ./src/udr/... 
          go vet ./src/n3iwf/... 
          go vet ./src/upf/... 
          
          cd /tmp/gtp5g
          make
          sudo -E make uninstall || true
          sudo -E make install 
          
          cd /tmp/free5gc
          go build -o bin/amf -x src/amf/amf.go
          go build -o bin/ausf -x src/ausf/ausf.go
          go build -o bin/nrf -x src/nrf/nrf.go
          go build -o bin/nssf -x src/nssf/nssf.go
          go build -o bin/pcf -x src/pcf/pcf.go
          go build -o bin/smf -x src/smf/smf.go
          go build -o bin/udm -x src/udm/udm.go
          go build -o bin/udr -x src/udr/udr.go 
          go build -o bin/n3iwf -x src/n3iwf/n3iwf.go
          
          cd /tmp/free5gc/src/upf
          rm -rf build 
          mkdir -p build 
          cd ./build 
          cmake .. 
          make 
          
          cd /tmp/free5gc
          sudo -E ./test.sh TestRegistration
          sudo -E ./test.sh TestGUTIRegistration 
          sudo -E ./test.sh TestServiceRequest 
          sudo -E ./test.sh TestXnHandover
          sudo -E ./test.sh TestDeregistration
          sudo -E./test.sh TestPDUSessionReleaseRequest
          sudo -E ./test.sh TestPaging
          sudo -E ./test.sh TestReSynchronisation
          
          rm -rf testkeylog/  
          
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - name: Check out free5gc 
#        uses: actions/checkout@v2

      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: echo Hello, world!

      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
